### PR TITLE
Compcars for dataset creation

### PR DESCRIPTION
**Pull request by tiffapedia**
Please do PR#25 before doing this PR

### CODE REVIEW

**Comment by agude** [comment]
Looks like you might have some commits from PR #25 at the beginning. Can you pull out just the commits needed for CompCars and push those to this branch? Thanks!

**Comment by agude** [comment]
@tiffapedia Could you rebase now that I've merged #25?

**Comment by tiffapedia** [comment]
Yup, it is already rebased.

**Comment by agude** [comment]
Thanks for all the work @tiffapedia! Looks good!

**Pull request merged**
